export const projectDocsConfig = [
  {
    slug: 'aulas-de-projeto',
    title: 'Aulas de Projeto',
    description: 'Evolução da interação homem-computador e autonomia dos sistemas',
    icon: 'BookOpen',
    color: '#f59e0b',
    file: '/docs/aulas-de-projeto.md',
    order: 1,
  },
  {
    slug: 'briefing-moburb',
    title: 'MobUrb - Briefing',
    description: 'Visão geral e escopo da plataforma MobUrb',
    icon: 'FileText',
    color: '#f59e0b',
    file: '/docs/briefing-moburb.md',
    order: 2,
  },
  {
    slug: 'moburb-requisitos',
    title: 'MobUrb - Requisitos',
    description: 'Engenharia de requisitos do projeto MobUrb',
    icon: 'ClipboardList',
    color: '#f59e0b',
    file: '/docs/moburb-requisitos.md',
    order: 3,
  },
  {
    slug: 'moburb-caso-de-uso',
    title: 'MobUrb - Caso de Uso',
    description: 'UML e casos de uso do MobUrb',
    icon: 'GitBranch',
    color: '#f59e0b',
    file: '/docs/moburb-caso-de-uso.md',
    order: 4,
  },
  {
    slug: 'uml-classes',
    title: 'Orientação a Objetos',
    description: 'Programação orientada a objetos e UML de classes',
    icon: 'Boxes',
    color: '#f59e0b',
    file: '/docs/uml-classes.md',
    order: 5,
  },
  {
    slug: 'arquitetura',
    title: 'Arquitetura de Software',
    description: 'Estrutura, padrões e princípios de arquitetura',
    icon: 'Layers',
    color: '#f59e0b',
    file: '/docs/arquitetura.md',
    order: 6,
  },
]

export const docsConfig = [
  {
    slug: 'algoritmos',
    title: 'Algoritmos',
    description: 'Lógica de programação e pensamento computacional',
    icon: 'Brain',
    color: '#a78bfa',
    file: '/docs/algoritmos.md',
    order: 1,
  },
  {
    slug: 'html',
    title: 'HTML',
    description: 'Estruturação de páginas web',
    icon: 'Code',
    color: '#f97316',
    file: '/docs/html.md',
    order: 2,
  },
  {
    slug: 'css',
    title: 'CSS',
    description: 'Estilização e layout visual',
    icon: 'Palette',
    color: '#3b82f6',
    file: '/docs/css.md',
    order: 3,
  },
  {
    slug: 'javascript',
    title: 'JavaScript',
    description: 'Programação web e interatividade',
    icon: 'Zap',
    color: '#eab308',
    file: '/docs/javascript.md',
    order: 4,
  },
  {
    slug: 'bootstrap',
    title: 'Bootstrap',
    description: 'Framework CSS responsivo',
    icon: 'Layout',
    color: '#8b5cf6',
    file: '/docs/bootstrap.md',
    order: 5,
  },
  {
    slug: 'react',
    title: 'React',
    description: 'Interfaces dinâmicas com componentes',
    icon: 'Atom',
    color: '#06b6d4',
    file: '/docs/react.md',
    order: 6,
  },
  {
    slug: 'sql',
    title: 'SQL',
    description: 'Banco de dados e consultas',
    icon: 'Database',
    color: '#14b8a6',
    file: '/docs/sql.md',
    order: 7,
  },
  {
    slug: 'csharp',
    title: 'C#',
    description: 'Programação orientada a objetos',
    icon: 'Cpu',
    color: '#10b981',
    file: '/docs/csharp.md',
    order: 8,
  },
  {
    slug: 'nodejs',
    title: 'Node.js',
    description: 'JavaScript no servidor',
    icon: 'Server',
    color: '#84cc16',
    file: '/docs/nodejs.md',
    order: 9,
  },
]
